/**
 * Cranach API
 * API to retrieve data from the Lucas Cranach Archive 
 *
 * OpenAPI spec version: 1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class InventoryNumberGet200Response {
    'winner'?: InventoryNumberGet200ResponseWinnerEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "winner",
            "baseName": "winner",
            "type": "InventoryNumberGet200ResponseWinnerEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InventoryNumberGet200Response.attributeTypeMap;
    }

    public constructor() {
    }
}


export type InventoryNumberGet200ResponseWinnerEnum = "X" | "O" | "DRAW" | "NONE" ;

