openapi: '3.1.0'
info:
  title: Cranach API
  description: |
    API to retrieve data from the Lucas Cranach Archive
  version: '1.3'
servers:
  - url: https://api.server.test/v1
paths:
  /:
    get:
      responses:
        '200':
          description: Returns a list of all items
